name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure and build
        run: |
          cmake -Bbuild
          cmake --build build

      - name: Test
        run: cmake --build build --target test
