name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: 'CMakeLists.txt'

      - name: Build
        run: cmake --build .

      - name: Test
        run: cmake --build . --target test
